apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: tilin.azurecr.io/flask-datta-able:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-acr-secret

