pipeline {
    agent any

    environment {
        // Define environment variables here
        DOCKER_IMAGE = 'flask-datta-able:latest'
        REGISTRY = 'tilin.azurecr.io'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building Docker Image'
                script {
                    // Build your Docker image
                    sh 'docker build -t flask-datta-able:latest /Users/jonathanhernandez/capstone_TC/flask-datta-able'

                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running Tests'
                // Add commands to run your tests here
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying to Kubernetes'
                script {
                    // Use kubectl to deploy to Kubernetes
                    sh '''
                        ls -l manifest/
                        kubectl apply -f /Users/jonathanhernandez/capstone_TC/flask-datta-able/manifest/deployment.yaml
                        kubectl apply -f /Users/jonathanhernandez/capstone_TC/flask-datta-able/manifest/service.yaml
                        '''
                }
            }
        }
    }
}
